# ==========================
# MOMENTUM CONFIG
# ==========================

ALERT_SCORE = 75

PRICE_WEIGHT = 30
VOLUME_WEIGHT = 30
TRADE_SPEED_WEIGHT = 20
ACTIVITY_WEIGHT = 20

PRICE_LOOKBACK = 20
MIN_PRICE_MOVE = 3.0

COOLDOWN_SECONDS = 900

WEBSOCKET_BATCH_SIZE = 50